POST http://localhost:8080/api/blogs/
Content-Type: application/json

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2
  }  